### ISSUE TITLE
Failure to detect extent --> crash

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-studio-classic#1111]
With a postgis layer and the following yml, I was able to browse my source but I couldn't export it

``` yml
    Datasource: 
      dbname: grandcanyon
      extent: -12690510.8526189,4231480.18898259,-12356540.8956021,4369642.09962137
      geometry_field: geometry
      geometry_table: ''
      host: ''
      key_field: ''
      max_size: 512
      password: ''
      port: ''
      table: |-
        (
          select 
            id, 
            unit, 
            unitname, 
            description,
            st_simplify(geom, !pixel_width!) as geometry
          from geopolys
          where geom && !bbox!
        ) as data
      type: postgis
      user: ''
```

Failure occurred in [lib/source.js](https://github.com/mapbox/mapbox-studio/blob/953ecc35ff6eca3fb5f1caf099ec46f85e86c60c/lib/source.js#L310) when `extent` was undefined. 

[Requesting extent from mapnik-omnivore](https://github.com/mapbox/mapbox-studio/blob/953ecc35ff6eca3fb5f1caf099ec46f85e86c60c/lib/source.js#L306) was returning an error:

```
{ [Error: Error obtaining extent of Mapnik datasource.] code: 'EINVALID' }
```
