### ISSUE TITLE
Be able to set different 'Viewports' to export to image

### ISSUE THREAD

**Issue by antoniolocandro** [mapbox/mapbox-studio-classic#1186]
I think it would be great if you can have different 'viewports' at different parts of the map to export like bookmarks.

Use case. I styled a US map but needed to export 3 different images...Alaska, Hawaii and Continental USA, current procedure is I need to set the export box each time I needed one, but what if I tweak something and want to export again? I would need to do the process again which is kind of time consuming at present.

**Comment by samanpwbb** [comment]
Hey @antoniolocandro this feature exists:

![screen_shot_2015-02-12_at_11_43_55_am](https://cloud.githubusercontent.com/assets/108094/6172068/9bb67836-b2ac-11e4-881b-bd040d2f4505.png)

It will be saved to "places":

![screen shot 2015-02-12 at 11 44 03 am](https://cloud.githubusercontent.com/assets/108094/6172073/a25d3fd0-b2ac-11e4-9a52-753b22acf0fe.png)

And you can actually copy + paste these bookmarks from the bookmarks.yml file in the project directory:

``` yml
- place_name: Budapest, Budapest, Hungary
  zoom: 13
  center: 
    - 47.493486685981615
    - 19.038963317871094
  tags: 
    - userbookmark
  index: 0
- place_name: Bratislava I, Bratislavský kraj, Slovakia
  zoom: 13
  center: 
    - 48.14232249263615
    - 17.11395263671875
  tags: 
    - userbookmark
  index: 1
- place_name: Budweis, Jihočeský, Czech Republic
  zoom: 13
  center: 
    - 48.979146659023996
    - 14.46950912475586
  tags: 
    - userbookmark
  index: 2
- place_name: London, SW1H 9NQ, City of Westminster, United Kingdom
  zoom: 12
  center: 
    - 51.49987377454688
    - -0.1325225830078125
  tags: 
    - userbookmark
  index: 3
```
