### ISSUE TITLE
Custom font rule breaks initial save

### ISSUE THREAD

**Issue by duncangraham** [mapbox/mapbox-studio-classic#978]
I creating a new project, and added the rule for custom fonts

``` CSS
Map {
    /* assumes fonts are in the style project's base directory */
    font-directory: url('');
}
```

Then I tried to save the project and went through the following process

![fonts](https://cloud.githubusercontent.com/assets/865298/4849811/6ecd945c-6064-11e4-9906-bac85e60c634.gif)

It seems like the project saved (a new project directory was created), but I still see initial Save as option, and can't use the original namespace I had chosen
